maxio-com/stoplight-platform-developer-docs

docs/announcements/2022-12-07-Preserve-Period-For-Subscriptions-With-Allocated-Components-During-Migration-Preview.md, toc.json
Related PR: https://github.com/maxio-com/chargify/pull/22107
=> [announcement] Preserve Period for Subscriptions with Allocated Components During Migration Preview

docs/announcements/2023-01-10-Ability-To-Sort-Results-For-List-Metadata-For-Resource-Type-Endpoint.md, toc.json
https://github.com/maxio-com/chargify/pull/22293
=> [announcement] Added ability to sort the results of List Metadata for Resource Type

docs/announcements/2023-01-16-Ability-To-Sort-Results-For-List-Metafields-Endpoint.md, toc.json
https://chargify.atlassian.net/browse/SUBB-201
=> [announcement] Added ability to sort results for List List Metafields endpoint

docs/announcements/2023-01-18-Ability-To-Set-Custom-Settings-For-Applying-Prepayments-To-Invoices.md, toc.json
https://chargify.atlassian.net/browse/SUBB-145?focusedCommentId=39207
=> [announcement] Ability to set custom settings for applying prepayments to invoices

docs/announcements/2023-01-24-Renewal-Success-And-Renewal-Failure-Events-Changes.md, toc.json
https://chargify.atlassian.net/browse/SUBB-198
=> [announcement] Renewal Success and Renewal Failure events changes

docs/announcements/2023-01-30-Access-Denied-401-HTTP-Responses-In-UI-And-API.md, toc.json
Details:
- https://maxio.slack.com/archives/C027XP6QJD8/p1675179435343289
- https://maxio.slack.com/archives/C028ME4G1PA/p1675083792535679
=> [announcement] 2023-01-30 "Access Denied" 401 HTTP responses in UI and API

docs/chargify.js/Version-History.md
Set latest ch.js version as 2023-02-02 "[internal] improve ACH flow"
=> Set latest ch.js version as 2023-02-02

docs/announcements/2023-02-17-temp.md
Added an announcement about webhooks for reactivations
=> Added docs/announcements/2023-02-17

docs/announcements/2023-02-17-temp.md
Reverts maxio-com/stoplight-platform-developer-docs#53
=> Revert "Added docs/announcements/2023-02-17"

docs/announcements/2023-02-28-Increase-in-Declines-from-Stripe-Gateway.md, toc.json
=> [announcement] 2023-02-28 Increase in Declines from Stripe Gateway 

docs/chargify.js/Version-History.md
Related PR: https://maxioevolution.atlassian.net/browse/PAYM-187
[feature] security enhancements
=> set latest Chargify.js version to 2023-03-06

docs/chargify.js/Version-History.md
Related PR: https://maxioevolution.atlassian.net/browse/PAYM-225
[feature] allow to populate country & state dropdowns with full names
=> set latest Chargify.js version to 2023-03-13

docs/advanced/Expert-Usage.md, docs/basics/Components.md, docs/basics/Signups.md, docs/basics/Subscriptions.md, docs/basics/Sync.md, docs/chargify-direct/Migrating-to-Chargify.js.md, docs/chargify-direct/Signups.md, docs/chargify.js/Chargify.js-Configurations.md, docs/chargify.js/Examples.md, docs/chargify.js/Gateway-Support.md, docs/chargify.js/Overview.md, docs/ecosystem/Ecosystem.md, docs/getting-started/API-Guidelines.md, docs/getting-started/Authentication.md, docs/getting-started/Overview.md, docs/getting-started/Products.md, docs/getting-started/SitesSubdomains.md
Fixed broken URLs in developer documentation abstracted from this [sheet](https://docs.google.com/spreadsheets/d/1jV4B6avZMHBhFmsngMKzVyBqY4atQzwX/edit?usp=sharing&ouid=104771532934771360790&rtpof=true&sd=true)
=> DE 261 - Fix various broken URL

docs/announcements/2023-05-10-SSL-Badge-Removal.md, toc.json
https://maxioevolution.atlassian.net/browse/SUB-2849
Add announcement for SSL Badge Removal
=> [announcement] SSL Badge Removal

docs/announcements/2023-05-18-Change-in-The-Refund_Success-and-Refund_Failure-Webhooks.md, toc.json
Reference link:
https://maxioevolution.atlassian.net/browse/SUB-2533
=> [announcement] Change in the refund_success and refund_failure webhooks

docs/chargify.js/Version-History.md
[feature] add public method `isPaymentProfileProvided` that securely checks the presence of payment profile details in Chargify.js instance
=> Set latest ch.js version to 2023-05-25

docs/chargify.js/Version-History.md
https://maxioevolution.atlassian.net/browse/PAYM-362
[bugfix] fix address fields incorrect behaviours
=> set latest ch.js version to 2023-07-11

docs/chargify.js/Version-History.md
[PAYM-644](https://maxioevolution.atlassian.net/browse/PAYM-644)
[PAYM-644]: https://maxioevolution.atlassian.net/browse/PAYM-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> set latest ch.js version to 2023-07-24

docs/chargify.js/Chargify.js-Configurations.md
[Jira Issue](https://maxioevolution.atlassian.net/browse/PAYM-620)
=> Add info about Plaid Configuration option to Chargify.js

docs/chargify.js/Chargify.js-Configurations.md
corresponding JIRA ticket: https://maxioevolution.atlassian.net/browse/PAYM-606
=> [documentation] DOC-21 update publicKey format in the examples

docs/chargify.js/Version-History.md
https://maxioevolution.atlassian.net/browse/PAYM-707
[internal] add option to pass pspToken when used on PSP
=> set latest ch.js version to 2023-09-05

docs/chargify.js/Version-History.md
https://maxioevolution.atlassian.net/browse/PAYM-703
[feature] Support for Plaid using maxp gateway #190
=> set latest ch.js version to 2023-09-12

docs/chargify.js/Overview.md
Jira ticket: https://maxioevolution.atlassian.net/browse/PAYM-831
=> Add examples of JWT token creation in python and java

docs/chargify.js/Version-History.md
https://maxioevolution.atlassian.net/browse/PAYM-903
[internal] Add 'maxp_ach' internal type #195
=> set latest ch.js version to 2023-11-09

docs/chargify.js/Version-History.md
https://maxioevolution.atlassian.net/browse/PAYM-653
https://maxioevolution.atlassian.net/browse/PAYM-1165
[feature] Add BACS support #199
=> Set latest ch.js version

docs/chargify.js/Chargify.js-Configurations.md, docs/chargify.js/Examples.md
Add examples for Stripe BACS Direct Debit.
=> [documentation] Add Stripe BACS Direct Debit info
